"""empty message

Revision ID: a94ad7a25f05
Revises: cbafa0c65961
Create Date: 2019-01-28 23:43:26.793318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94ad7a25f05'
down_revision = 'cbafa0c65961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('pos_plan', sa.Integer(), nullable=False),
    sa.Column('pos_fact', sa.Integer(), nullable=False),
    sa.Column('nps_plan', sa.Float(), nullable=False),
    sa.Column('nps_fact', sa.Float(), nullable=False),
    sa.Column('refund_fz', sa.Boolean(), nullable=False),
    sa.Column('fz_plan', sa.Float(), nullable=False),
    sa.Column('fz_fact', sa.Float(), nullable=False),
    sa.Column('sms_plan', sa.Float(), nullable=False),
    sa.Column('sms_fact', sa.Float(), nullable=False),
    sa.Column('kr_plan', sa.Integer(), nullable=False),
    sa.Column('kr_fact', sa.Integer(), nullable=False),
    sa.Column('box_plan', sa.Integer(), nullable=False),
    sa.Column('box_fact', sa.Integer(), nullable=False),
    sa.Column('ops_plan', sa.Integer(), nullable=False),
    sa.Column('ops_fact', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
