"""empty message

Revision ID: eef3a8a52306
Revises: 
Create Date: 2019-02-04 23:00:12.090329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef3a8a52306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('pos_plan', sa.Integer(), nullable=False),
    sa.Column('pos_fact', sa.Integer(), nullable=False),
    sa.Column('nps_plan', sa.Float(), nullable=False),
    sa.Column('nps_fact', sa.Float(), nullable=False),
    sa.Column('refund_fz', sa.Boolean(), nullable=False),
    sa.Column('fz_plan', sa.Float(), nullable=False),
    sa.Column('fz_fact', sa.Float(), nullable=False),
    sa.Column('sms_plan', sa.Float(), nullable=False),
    sa.Column('sms_fact', sa.Float(), nullable=False),
    sa.Column('kr_plan', sa.Integer(), nullable=False),
    sa.Column('kr_fact', sa.Integer(), nullable=False),
    sa.Column('box_plan', sa.Integer(), nullable=False),
    sa.Column('box_fact', sa.Integer(), nullable=False),
    sa.Column('ops_plan', sa.Integer(), nullable=False),
    sa.Column('ops_fact', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_middle_name'), 'employees', ['middle_name'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_weight', sa.Integer(), nullable=False),
    sa.Column('nps_weight', sa.Integer(), nullable=False),
    sa.Column('fz_weight', sa.Integer(), nullable=False),
    sa.Column('refund_fz_weight', sa.Integer(), nullable=False),
    sa.Column('sms_weight', sa.Integer(), nullable=False),
    sa.Column('kr_weight', sa.Integer(), nullable=False),
    sa.Column('box_weight', sa.Integer(), nullable=False),
    sa.Column('ops_weight', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('employee', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee'], ['employees.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['rating'], ['ratings.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('employee', 'rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_employees_middle_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
